version: '3.8'

services:

  server:
    build:
      context: ./vizx-learning-hub-server
      dockerfile: Dockerfile
    ports:
      - "3000"
   
    volumes:
      - ./vizx-learning-hub-server/uploads:/app/uploads

  client:
    build:
      context: ./vizx_learning_hub_client
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=https://api.academy.vizxglobal.com  # REPLACE WITH YOUR ACTUAL API DOMAIN
    ports:
      - "80"
    depends_on:
      - server
